<a href="https://colab.research.google.com/github/cnrywjd11/TensorFlow_for_Deep_Learning_Bootcamp/blob/week1%2Fchiwon/00_extra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 📖 00. TensorFlow Fundamentals Extra-curriculum

* Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?
* Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
* Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.

In [1]:
import tensorflow as tf
tf.__version__

'2.17.0'

In [5]:
string = "Read through the list of TensorFlow Python APIs, pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does."

tf.strings.ngrams(string.split(" "), 3, '-')

<tf.Tensor: shape=(31,), dtype=string, numpy=
array([b'Read-through-the', b'through-the-list', b'the-list-of',
       b'list-of-TensorFlow', b'of-TensorFlow-Python',
       b'TensorFlow-Python-APIs,', b'Python-APIs,-pick',
       b'APIs,-pick-one', b'pick-one-we', b"one-we-haven't",
       b"we-haven't-gone", b"haven't-gone-through", b'gone-through-in',
       b'through-in-this', b'in-this-notebook,',
       b'this-notebook,-reverse', b'notebook,-reverse-engineer',
       b'reverse-engineer-it', b'engineer-it-(write', b'it-(write-out',
       b'(write-out-the', b'out-the-documentation',
       b'the-documentation-code', b'documentation-code-for',
       b'code-for-yourself)', b'for-yourself)-and',
       b'yourself)-and-figure', b'and-figure-out', b'figure-out-what',
       b'out-what-it', b'what-it-does.'], dtype=object)>

In [6]:
bills = [2660,
50000,
11090,
14000,
5000,
2480,
1000,
11000,
2000,
102000]

In [8]:
B = tf.constant(bills)
tf.reduce_sum(B).numpy()

201230

In [4]:
mnist = tf.keras.datasets.mnist

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [11]:
x_train.shape

(60000, 28, 28)

In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [7]:
predictions= model(x_train[:1]).numpy()
predictions

array([[0.05805122, 0.10534797, 0.11893526, 0.1442427 , 0.07298326,
        0.11439426, 0.162047  , 0.0635749 , 0.08537848, 0.07504488]],
      dtype=float32)

In [12]:
x_train[:1].shape

(1, 28, 28)

In [13]:
tf.nn.softmax(predictions).numpy()

array([[0.09583863, 0.10048039, 0.10185497, 0.10446554, 0.09728043,
        0.10139349, 0.10634214, 0.09636948, 0.09849375, 0.09748118]],
      dtype=float32)

In [14]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [16]:
loss_fn(y_train[:1], predictions).numpy()

2.2887464

In [17]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [18]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/nn.py:609: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.8609 - loss: 0.4766
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9539 - loss: 0.1520
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9680 - loss: 0.1083
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9739 - loss: 0.0869
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9774 - loss: 0.0727


In [19]:
model.evaluate(x_test, y_test, verbose=2)

/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/nn.py:609: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


313/313 - 2s - 6ms/step - accuracy: 0.9763 - loss: 0.0745


[0.0745430588722229, 0.9763000011444092]

In [20]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [21]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0853378 , 0.0853378 , 0.08533806, 0.08534453, 0.0853378 ,
        0.08533785, 0.0853378 , 0.23195256, 0.08533788, 0.08533788],
       [0.08533856, 0.08534927, 0.23194069, 0.08533863, 0.08533856,
        0.08533929, 0.08533917, 0.08533856, 0.08533873, 0.08533856],
       [0.08535693, 0.23164998, 0.08540773, 0.08535831, 0.08535847,
        0.08535884, 0.0853596 , 0.08540556, 0.0853876 , 0.08535694],
       [0.23195495, 0.08533765, 0.08534242, 0.08533766, 0.08533766,
        0.08533778, 0.08533784, 0.08533768, 0.08533789, 0.08533852],
       [0.08536077, 0.08536071, 0.08536099, 0.08536071, 0.23158981,
        0.08536071, 0.08536085, 0.08536524, 0.08536076, 0.08551947]],
      dtype=float32)>