In [55]:
import tensorflow as tf
print(tf.__version__)
import numpy as np
print(np.__version__)

2.17.0
1.26.4


#### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [16]:
vector = tf.constant([7])
vector.ndim

1

In [17]:
scalar = tf.constant(7)
scalar.ndim

0

In [18]:
matrix = tf.constant([[1, 2], [3, 4]])
matrix.ndim

2

In [19]:
tensor = tf.constant([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

#### 2. Find the shape, rank and size of the tensors you created in 1.

In [21]:
vector.shape, tf.rank(vector), tf.size(vector)

(TensorShape([1]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [22]:
scalar.shape, tf.rank(scalar), tf.size(scalar)

(TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [23]:
matrix.shape, tf.rank(matrix), tf.size(matrix)

(TensorShape([2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [24]:
tensor.shape, tf.rank(tensor), tf.size(tensor)

(TensorShape([3, 2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

#### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [32]:
A = tf.random.uniform(shape=[5, 300])
A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.95831835, 0.01680839, 0.3156035 , ..., 0.67105925, 0.76730955,
        0.20125735],
       [0.09921694, 0.02475083, 0.47242153, ..., 0.9631474 , 0.34333456,
        0.8129494 ],
       [0.08817983, 0.9311962 , 0.2293179 , ..., 0.41450226, 0.008304  ,
        0.02438807],
       [0.54814565, 0.37019622, 0.5272658 , ..., 0.8656951 , 0.19644582,
        0.5959221 ],
       [0.8964087 , 0.15288067, 0.3360591 , ..., 0.5725572 , 0.4094149 ,
        0.40059018]], dtype=float32)>

In [34]:
B = tf.random.uniform(shape=[5, 300])
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.14241445, 0.40161622, 0.33360183, ..., 0.467453  , 0.4010433 ,
        0.77402675],
       [0.68600106, 0.36842024, 0.838217  , ..., 0.5757059 , 0.321252  ,
        0.4654348 ],
       [0.51995134, 0.3815695 , 0.59582543, ..., 0.09222043, 0.6600671 ,
        0.00907719],
       [0.11020112, 0.18113029, 0.16872919, ..., 0.05145729, 0.21334374,
        0.12166667],
       [0.90618634, 0.7663641 , 0.9128959 , ..., 0.90221953, 0.00464523,
        0.03899753]], dtype=float32)>

#### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [36]:
tf.matmul(A, tf.reshape(B, shape=(300, 5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.492294, 71.20219 , 73.33479 , 71.580414, 75.46095 ],
       [71.42946 , 76.49174 , 71.894325, 75.42511 , 75.00824 ],
       [77.53951 , 77.31646 , 81.22734 , 78.52912 , 82.55268 ],
       [73.59802 , 76.68869 , 77.45349 , 76.0298  , 78.84175 ],
       [73.446686, 74.69656 , 75.69572 , 76.62387 , 77.6922  ]],
      dtype=float32)>

#### 5. Multiply the two tensors you created in 3 using dot product.

In [41]:
tf.tensordot(A, tf.transpose(B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.94975 , 73.56144 , 69.62314 , 72.18502 , 66.91785 ],
       [77.15861 , 77.202545, 73.34158 , 75.209465, 72.46777 ],
       [83.9196  , 81.31598 , 81.30655 , 81.60316 , 74.21117 ],
       [77.39996 , 75.43019 , 78.49779 , 76.20861 , 72.63331 ],
       [78.93554 , 77.90604 , 76.70812 , 76.22255 , 73.47687 ]],
      dtype=float32)>

#### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [43]:
C = tf.random.uniform(shape=[224, 224, 3])
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.12780273, 0.86230123, 0.41563296],
        [0.10028672, 0.6078365 , 0.79052174],
        [0.06068337, 0.85674644, 0.72001266],
        ...,
        [0.42501688, 0.777889  , 0.7029644 ],
        [0.00265503, 0.4391595 , 0.89044964],
        [0.63493025, 0.87544703, 0.943701  ]],

       [[0.6613052 , 0.37710202, 0.51483595],
        [0.50989354, 0.9679649 , 0.45765674],
        [0.2590027 , 0.3557694 , 0.26365137],
        ...,
        [0.3261726 , 0.49975753, 0.1813755 ],
        [0.6064073 , 0.8051214 , 0.320701  ],
        [0.32923293, 0.5298729 , 0.39044487]],

       [[0.34140837, 0.47335994, 0.01272404],
        [0.47659898, 0.47509444, 0.8660991 ],
        [0.16929126, 0.09049737, 0.09263301],
        ...,
        [0.15332878, 0.2546159 , 0.9531114 ],
        [0.10869956, 0.5302429 , 0.8690088 ],
        [0.6384195 , 0.19085515, 0.35851824]],

       ...,

       [[0.62105274, 0.22180116, 0.71062243],
        [0.27

#### 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [51]:
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=float32, numpy=3.8146973e-06>

In [50]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999919>

#### 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [52]:
D = tf.random.uniform(shape=[1, 224, 224, 3])
D

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.5749372 , 0.19900596, 0.7038239 ],
         [0.05541027, 0.5884645 , 0.5430788 ],
         [0.9185413 , 0.37144518, 0.84554374],
         ...,
         [0.6570301 , 0.7645861 , 0.48230588],
         [0.41497958, 0.4241538 , 0.5199896 ],
         [0.59315014, 0.23632371, 0.15606153]],

        [[0.34459436, 0.24155474, 0.8630327 ],
         [0.92559505, 0.41881108, 0.9492458 ],
         [0.21597803, 0.15805602, 0.9682605 ],
         ...,
         [0.45298254, 0.6097312 , 0.45232892],
         [0.04503286, 0.48371267, 0.7752477 ],
         [0.644374  , 0.65862846, 0.11632323]],

        [[0.18631506, 0.29340136, 0.3898226 ],
         [0.8457128 , 0.86194694, 0.05938876],
         [0.22856331, 0.74509835, 0.32373703],
         ...,
         [0.03299081, 0.8350847 , 0.77849007],
         [0.5707276 , 0.7097032 , 0.07139933],
         [0.6495327 , 0.17728817, 0.2139225 ]],

        ...,

        [[0.79031277, 0.3867849 , 

In [53]:
tf.squeeze(D)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5749372 , 0.19900596, 0.7038239 ],
        [0.05541027, 0.5884645 , 0.5430788 ],
        [0.9185413 , 0.37144518, 0.84554374],
        ...,
        [0.6570301 , 0.7645861 , 0.48230588],
        [0.41497958, 0.4241538 , 0.5199896 ],
        [0.59315014, 0.23632371, 0.15606153]],

       [[0.34459436, 0.24155474, 0.8630327 ],
        [0.92559505, 0.41881108, 0.9492458 ],
        [0.21597803, 0.15805602, 0.9682605 ],
        ...,
        [0.45298254, 0.6097312 , 0.45232892],
        [0.04503286, 0.48371267, 0.7752477 ],
        [0.644374  , 0.65862846, 0.11632323]],

       [[0.18631506, 0.29340136, 0.3898226 ],
        [0.8457128 , 0.86194694, 0.05938876],
        [0.22856331, 0.74509835, 0.32373703],
        ...,
        [0.03299081, 0.8350847 , 0.77849007],
        [0.5707276 , 0.7097032 , 0.07139933],
        [0.6495327 , 0.17728817, 0.2139225 ]],

       ...,

       [[0.79031277, 0.3867849 , 0.21375918],
        [0.25

#### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [69]:
E = tf.constant(np.random.randint(0, 10, size=10))
E

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([9, 2, 8, 6, 7, 6, 9, 6, 8, 8])>

In [70]:
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

#### 10. One-hot encode the tensor you created in 9.

In [71]:
tf.one_hot(E, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>