## 🛠 Exercises

In [10]:
import tensorflow as tf

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [11]:
# vector
vector = tf.constant(tf.ones((10, )), dtype=tf.float32)
vector

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [12]:
# scalar
scalar = tf.constant(10, dtype=tf.float32)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [13]:
# matrix
matrix = tf.constant(tf.ones((10, 10, )), dtype=tf.float32)
matrix

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [14]:
# tensor
tensor = tf.constant(tf.ones((10, 10, 10, )), dtype=tf.float32)
tensor

<tf.Tensor: shape=(10, 10, 10), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.,

2. Find the shape, rank and size of the tensors you created in 1.

In [23]:
print(tensor.shape, tensor.ndim, tf.size(tensor))

(10, 10, 10) 3 tf.Tensor(1000, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [24]:
tensor1 = tf.constant(np.random.random((5, 300)))
tensor2 = tf.constant(np.random.random((5, 300)))

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [25]:
tf.matmul(tf.transpose(tensor1), tensor2)

<tf.Tensor: shape=(300, 300), dtype=float64, numpy=
array([[0.58086759, 0.48753146, 0.95492128, ..., 0.86608919, 0.94872679,
        0.75773458],
       [1.6966154 , 0.73101779, 1.72729853, ..., 1.74578131, 1.80495071,
        1.30616165],
       [1.35643095, 0.98932691, 1.10436485, ..., 1.40755844, 1.3723707 ,
        0.92932478],
       ...,
       [1.09699564, 0.63817586, 1.54403487, ..., 1.75992914, 1.35505609,
        1.51698237],
       [1.31426567, 0.69022871, 1.04265726, ..., 1.31520907, 1.12286519,
        0.78306853],
       [1.39818539, 0.61690292, 1.52247056, ..., 2.0594413 , 1.1788642 ,
        1.51092833]])>

5. Multiply the two tensors you created in 3 using dot product.

In [26]:
tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float64, numpy=
array([[0.58086759, 0.48753146, 0.95492128, ..., 0.86608919, 0.94872679,
        0.75773458],
       [1.6966154 , 0.73101779, 1.72729853, ..., 1.74578131, 1.80495071,
        1.30616165],
       [1.35643095, 0.98932691, 1.10436485, ..., 1.40755844, 1.3723707 ,
        0.92932478],
       ...,
       [1.09699564, 0.63817586, 1.54403487, ..., 1.75992914, 1.35505609,
        1.51698237],
       [1.31426567, 0.69022871, 1.04265726, ..., 1.31520907, 1.12286519,
        0.78306853],
       [1.39818539, 0.61690292, 1.52247056, ..., 2.0594413 , 1.1788642 ,
        1.51092833]])>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [27]:
tensor1 = tf.constant(np.random.random((224, 224, 3)))

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [28]:
print(tf.reduce_min(tensor1, axis=1), tf.reduce_max(tensor1, axis=1))

tf.Tensor(
[[2.84363988e-03 9.35522636e-03 7.05752595e-04]
 [2.33986605e-02 1.82616413e-03 4.29443439e-04]
 [8.61665761e-03 1.17936451e-03 2.32391427e-03]
 [1.02218582e-02 7.41261293e-04 5.87135522e-03]
 [9.88465508e-03 1.46504173e-04 1.15716018e-02]
 [3.64054800e-03 9.53249351e-03 2.57923929e-03]
 [9.06772004e-04 1.26236153e-03 8.51420615e-04]
 [3.28264696e-03 3.15319651e-03 1.50964500e-03]
 [4.97656625e-03 4.88800690e-03 1.11360923e-04]
 [3.77787116e-03 1.86934343e-03 2.17346289e-04]
 [1.48005031e-03 3.31067943e-03 5.65885087e-03]
 [3.79980954e-03 7.37210156e-03 1.50433602e-04]
 [8.31716613e-04 4.68399934e-03 1.95156330e-03]
 [1.08930007e-03 4.50300920e-03 1.26633579e-03]
 [2.13379417e-03 2.68736781e-03 1.42639348e-03]
 [3.05620083e-03 1.51021492e-02 1.26263552e-02]
 [1.77739863e-03 7.11848588e-04 6.74743875e-03]
 [7.10165779e-04 4.31124713e-03 5.04184120e-03]
 [4.17825755e-05 5.18927195e-03 1.81831773e-03]
 [2.52562756e-03 1.57527069e-03 6.42399639e-03]
 [5.23219365e-03 2.88541593e-

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [31]:
tensor2 = tensor1[tf.newaxis, ...]
tensor2.shape

TensorShape([1, 224, 224, 3])

In [32]:
tensor3 = tf.squeeze(tensor2)
tensor3.shape

TensorShape([224, 224, 3])

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [33]:
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tf.argmax(tensor1)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

10. One-hot encode the tensor you created in 9.

In [34]:
tf.one_hot(tensor1, 11)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

## 📖 Extra-curriculum

* Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?
* Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
* Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.

### 1

In [105]:
# tf.math.exp
# Computes exponential of x element-wise. y = e^x
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=tf.float32)
tf.exp(tensor1)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 2.0085537e+01, 5.4598148e+01,
       1.4841316e+02, 4.0342877e+02, 1.0966332e+03, 2.9809578e+03,
       8.1030840e+03, 2.2026465e+04], dtype=float32)>

### 2

In [106]:
@tf.function
def tf_function(grocery_bill):
  return tf.reduce_sum(grocery_bill)

grocery_bill = tf.constant([
    1000,
    2000,
    3000
])

tf_function(grocery_bill)

<tf.Tensor: shape=(), dtype=int32, numpy=6000>

### 3

In [107]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [108]:
import requests
requests.packages.urllib3.disable_warnings()
import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

In [109]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [110]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

/Users/user/Projects/ds-conversion-trainer/venv/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [111]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.04338488, 0.13068359, 0.1063771 , 0.10391325, 0.18642995,
        0.07352313, 0.15787943, 0.12338407, 0.03755378, 0.03687071]],
      dtype=float32)

In [112]:
tf.nn.softmax(predictions).numpy()

array([[0.09438144, 0.10299116, 0.10051799, 0.10027064, 0.10889559,
        0.09726924, 0.10583053, 0.10224212, 0.09383269, 0.09376863]],
      dtype=float32)

In [113]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [114]:
loss_fn(y_train[:1], predictions).numpy()

2.3302727

In [115]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [116]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/Users/user/Projects/ds-conversion-trainer/venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:635: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8571 - loss: 0.4832
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9554 - loss: 0.1532
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9675 - loss: 0.1089
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9725 - loss: 0.0889
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9779 - loss: 0.0712


In [117]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9804 - loss: 0.0625
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9815 - loss: 0.0581
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9834 - loss: 0.0500
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9850 - loss: 0.0452
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9859 - loss: 0.0438
313/313 - 0s - 512us/step - accuracy: 0.9789 - loss: 0.0760


[0.07598302513360977, 0.9789000153541565]

In [118]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [119]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533799, 0.08533799, 0.08533799, 0.08534639, 0.08533799,
        0.08533799, 0.08533799, 0.23194982, 0.08533799, 0.085338  ],
       [0.08533683, 0.08533734, 0.23196808, 0.08533685, 0.08533683,
        0.08533683, 0.08533683, 0.08533683, 0.08533683, 0.08533683],
       [0.08535147, 0.23173611, 0.08537206, 0.08535151, 0.08535279,
        0.08535147, 0.085352  , 0.08542395, 0.08535714, 0.08535147],
       [0.23196414, 0.08533706, 0.08533717, 0.08533709, 0.08533706,
        0.08533711, 0.085339  , 0.08533707, 0.08533706, 0.08533713],
       [0.0854104 , 0.08541039, 0.08541165, 0.08541041, 0.2307995 ,
        0.08541039, 0.08541039, 0.08541115, 0.08541041, 0.08591532]],
      dtype=float32)>