## 🛠 Exercises

In [1]:
import tensorflow as tf

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [2]:
# vector
vector = tf.constant(tf.ones((10, )), dtype=tf.float32)
vector

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [3]:
# scalar
scalar = tf.constant(10, dtype=tf.float32)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [4]:
# matrix
matrix = tf.constant(tf.ones((10, 10, )), dtype=tf.float32)
matrix

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [5]:
# tensor
tensor = tf.constant(tf.ones((10, 10, 10, )), dtype=tf.float32)
tensor

<tf.Tensor: shape=(10, 10, 10), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.,

2. Find the shape, rank and size of the tensors you created in 1.

In [6]:
print(tf.shape(vector), tf.rank(vector), tf.size(vector))

tf.Tensor([10], shape=(1,), dtype=int32) tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(10, shape=(), dtype=int32)


In [7]:
print(tf.shape(scalar), tf.rank(scalar), tf.size(scalar))

tf.Tensor([], shape=(0,), dtype=int32) tf.Tensor(0, shape=(), dtype=int32) tf.Tensor(1, shape=(), dtype=int32)


In [8]:
print(tf.shape(matrix), tf.rank(matrix), tf.size(matrix))

tf.Tensor([10 10], shape=(2,), dtype=int32) tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(100, shape=(), dtype=int32)


In [9]:
print(tf.shape(tensor), tf.rank(tensor), tf.size(tensor))

tf.Tensor([10 10 10], shape=(3,), dtype=int32) tf.Tensor(3, shape=(), dtype=int32) tf.Tensor(1000, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [10]:
tensor1 = tf.constant(np.random.random((5, 300)))
tensor2 = tf.constant(np.random.random((5, 300)))

NameError: name 'np' is not defined

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tf.matmul(tf.transpose(tensor1), tensor2)

5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [ ]:
tensor1 = tf.constant(np.random.random((224, 224, 3)))

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [ ]:
print(tf.reduce_min(tensor1, axis=1), tf.reduce_max(tensor1, axis=1))

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [ ]:
tensor2 = tensor1[tf.newaxis, ...]
tensor2.shape

In [ ]:
tensor3 = tf.squeeze(tensor2)
tensor3.shape

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [ ]:
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tf.argmax(tensor1)

10. One-hot encode the tensor you created in 9.

In [ ]:
tf.one_hot(tensor1, 11)

## 📖 Extra-curriculum

* Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?
* Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
* Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.

### 1

In [ ]:
# tf.math.exp
# Computes exponential of x element-wise. y = e^x
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=tf.float32)
tf.exp(tensor1)

### 2

In [ ]:
@tf.function
def tf_function(grocery_bill):
  return tf.reduce_sum(grocery_bill)

grocery_bill = tf.constant([
    1000,
    2000,
    3000
])

tf_function(grocery_bill)

### 3

In [11]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [12]:
import requests
requests.packages.urllib3.disable_warnings()
import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

In [13]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [14]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

/Users/user/Projects/ds-conversion-trainer/venv/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [15]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.20610441, 0.10609559, 0.08961423, 0.07256996, 0.13632353,
        0.05871494, 0.04902767, 0.04289041, 0.12970118, 0.10895805]],
      dtype=float32)

In [16]:
tf.nn.softmax(predictions).numpy()

array([[0.11106995, 0.10049936, 0.09885658, 0.09718591, 0.10358363,
        0.09584869, 0.09492466, 0.09434386, 0.10289993, 0.10078745]],
      dtype=float32)

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [18]:
loss_fn(y_train[:1], predictions).numpy()

2.3449845

In [19]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [20]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/Users/user/Projects/ds-conversion-trainer/venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:635: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8570 - loss: 0.4843
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9562 - loss: 0.1491
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9669 - loss: 0.1091
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 987us/step - accuracy: 0.9740 - loss: 0.0826
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9771 - loss: 0.0742


In [21]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 966us/step - accuracy: 0.9807 - loss: 0.0593
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9827 - loss: 0.0554
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 983us/step - accuracy: 0.9844 - loss: 0.0479
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9840 - loss: 0.0483
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 993us/step - accuracy: 0.9856 - loss: 0.0419
313/313 - 0s - 467us/step - accuracy: 0.9781 - loss: 0.0774


[0.07739464193582535, 0.9781000018119812]

In [22]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [23]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533674, 0.08533674, 0.08533674, 0.0853368 , 0.08533674,
        0.08533674, 0.08533674, 0.23196913, 0.08533674, 0.08533676],
       [0.08538629, 0.08572626, 0.23118329, 0.08538631, 0.08538629,
        0.08538629, 0.08538629, 0.08538629, 0.08538635, 0.08538629],
       [0.08533702, 0.23196468, 0.08533712, 0.08533704, 0.08533718,
        0.08533705, 0.08533703, 0.0853378 , 0.08533795, 0.08533702],
       [0.23196892, 0.08533676, 0.08533681, 0.08533676, 0.08533676,
        0.08533679, 0.08533686, 0.08533676, 0.08533676, 0.08533677],
       [0.08540715, 0.08540715, 0.08540717, 0.08540715, 0.23085132,
        0.08540715, 0.08540734, 0.08542169, 0.08540715, 0.08587672]],
      dtype=float32)>