## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [2]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [3]:
# Ex1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

vector = tf.constant([1,2,3])
scalar = tf.constant(1)
matrix = tf.constant([[1,2,3],[4,5,6]]) 
tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]]) 
vector, scalar, matrix, tensor

2024-11-14 15:13:45.971338: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Max
2024-11-14 15:13:45.971362: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 32.00 GB
2024-11-14 15:13:45.971369: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 10.67 GB
2024-11-14 15:13:45.971384: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-11-14 15:13:45.971395: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=int32)>)

In [4]:
# Ex2. Find the shape, rank and size of the tensors you created in 1.
print("vector : shape={}, rank={}, size={}".format(vector.shape, vector.ndim, tf.size(vector)))
print("scalar : shape={}, rank={}, size={}".format(scalar.shape, scalar.ndim, tf.size(scalar)))
print("matrix : shape={}, rank={}, size={}".format(matrix.shape, matrix.ndim, tf.size(matrix)))
print("tensor : shape={}, rank={}, size={}".format(tensor.shape, tensor.ndim, tf.size(tensor)))

vector : shape=(3,), rank=1, size=3
scalar : shape=(), rank=0, size=1
matrix : shape=(2, 3), rank=2, size=6
tensor : shape=(1, 3, 3), rank=3, size=9


In [5]:
# Ex3.  Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
random_A = tf.random.uniform(shape=(5,300))
random_B = tf.random.uniform(shape=(5,300))
print(random_A)
print(random_B)


tf.Tensor(
[[0.9337802  0.4932146  0.971915   ... 0.14808726 0.65912247 0.23958004]
 [0.78237784 0.77039635 0.5131935  ... 0.07094157 0.807251   0.86054444]
 [0.9451951  0.8251952  0.93685293 ... 0.35165513 0.5185801  0.08025777]
 [0.11546791 0.6995423  0.750859   ... 0.32129264 0.9909959  0.32122016]
 [0.91079235 0.40794837 0.9466622  ... 0.86728716 0.4775641  0.29764068]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.31179297 0.8263413  0.6849456  ... 0.56451845 0.44649565 0.41026497]
 [0.60833323 0.50973356 0.31043375 ... 0.50437474 0.6110033  0.7943536 ]
 [0.20573044 0.5442884  0.10470831 ... 0.18146193 0.26921892 0.71201587]
 [0.31422472 0.15571809 0.59350574 ... 0.21489167 0.96785796 0.13088453]
 [0.00473952 0.06306279 0.91214204 ... 0.7092078  0.93488145 0.7450988 ]], shape=(5, 300), dtype=float32)


In [6]:
# Ex4. Multiply the two tensors you created in 3 using matrix multiplication.
result = random_A @ tf.transpose(random_B) 
print(result)

tf.Tensor(
[[76.17342  78.764725 75.731705 72.29239  75.70853 ]
 [69.31658  75.116394 71.06091  70.186935 73.10719 ]
 [75.23542  75.22896  72.29024  67.72285  72.21751 ]
 [68.239586 71.706474 71.0289   65.431694 70.97731 ]
 [76.79858  80.60443  76.75188  71.736435 79.946884]], shape=(5, 5), dtype=float32)


In [7]:
# Ex5. Multiply the two tensors you created in 3 using dot product.
print(tf.tensordot(random_A, tf.transpose(random_B), axes=1))

tf.Tensor(
[[76.17342  78.764725 75.731705 72.29239  75.70853 ]
 [69.31658  75.116394 71.06091  70.186935 73.10719 ]
 [75.23542  75.22896  72.29024  67.72285  72.21751 ]
 [68.239586 71.706474 71.0289   65.431694 70.97731 ]
 [76.79858  80.60443  76.75188  71.736435 79.946884]], shape=(5, 5), dtype=float32)


In [8]:
# Ex6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
X = tf.random.uniform(shape=(224,224,3))
print(X)

tf.Tensor(
[[[0.31179297 0.8263413  0.6849456 ]
  [0.0067091  0.78749514 0.3906511 ]
  [0.29263055 0.99216926 0.95810425]
  ...
  [0.43970728 0.976676   0.8946736 ]
  [0.9747398  0.7011992  0.73613393]
  [0.4360633  0.7536833  0.01353109]]

 [[0.2823602  0.0927937  0.2424469 ]
  [0.92214036 0.1318667  0.18895125]
  [0.13469017 0.29916108 0.22880554]
  ...
  [0.10263181 0.3771491  0.7380618 ]
  [0.6484846  0.69211054 0.67284966]
  [0.43589175 0.48166    0.14082742]]

 [[0.41235518 0.45162737 0.6804353 ]
  [0.04887676 0.6775023  0.29143417]
  [0.3466624  0.17450547 0.38451958]
  ...
  [0.8667455  0.16113937 0.67500424]
  [0.8560462  0.48929954 0.97561824]
  [0.5725883  0.8036673  0.3923154 ]]

 ...

 [[0.68855166 0.3706571  0.03126299]
  [0.61133444 0.21750414 0.9080095 ]
  [0.20064199 0.31340492 0.85072494]
  ...
  [0.8053781  0.54289234 0.08450699]
  [0.6037886  0.0091573  0.14664805]
  [0.36727667 0.66913784 0.9003469 ]]

 [[0.4256966  0.88771296 0.6295724 ]
  [0.99141705 0.49446368 0

In [9]:
# ex7. Find the min and max values of the tensor you created in 6.
print(tf.reduce_min(X), tf.reduce_max(X))

tf.Tensor(4.053116e-06, shape=(), dtype=float32) tf.Tensor(0.99998736, shape=(), dtype=float32)


In [10]:
# ex8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
X = tf.random.normal(shape=(1,224,224,3))
print(X)
print(tf.squeeze(X))

tf.Tensor(
[[[[-4.2172405e-01 -4.2308071e-01 -8.0168909e-01]
   [-6.7317444e-01  4.3181294e-01  5.8552098e-01]
   [ 2.2246742e-01  1.5540966e+00 -8.0575699e-01]
   ...
   [-4.1951582e-01 -1.9153776e+00 -3.2545367e-01]
   [ 7.4074793e-01  4.1595727e-01 -3.2613239e-01]
   [ 1.3694730e+00 -5.1413178e-01  8.9835227e-01]]

  [[-9.9161202e-01  3.2992408e-02 -9.6722590e-03]
   [ 6.6796428e-01  7.2086483e-02  1.5072968e+00]
   [-1.3952900e+00 -1.2745913e+00  4.4905239e-01]
   ...
   [ 1.0815152e+00 -1.4982176e+00  1.1036540e+00]
   [ 1.4173114e-01 -2.0224410e-01  1.2116796e+00]
   [ 3.0588856e-01 -2.2433811e-01  1.8906660e-01]]

  [[-2.3447473e-03 -6.0212141e-01  2.8815624e-01]
   [-8.7414259e-01  1.2589243e-01  8.4852695e-01]
   [ 1.3035592e-02  8.1200939e-01  3.8276184e-01]
   ...
   [-7.5564623e-01 -9.1405547e-01  5.3718346e-01]
   [-1.9339793e+00  4.4547373e-01 -1.1475806e-01]
   [-4.6536487e-01  1.1215113e+00 -7.4444062e-01]]

  ...

  [[-9.8509151e-01 -5.2955246e-01  1.0837586e+00]
   [-

In [11]:
# ex9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
X = tf.random.uniform(shape=(10,), minval=0, maxval=10, dtype=tf.int32)
print(X)
print(tf.argmax(X))

tf.Tensor([9 1 8 2 0 8 5 2 1 8], shape=(10,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int64)


In [12]:
# ex10. One-hot encode the tensor you created in 9.
tf.one_hot(X, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>