In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.0


# Exercise

## 🛠 00 TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the **shape**, **rank** and **size** of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using **matrix multiplication**.
5. Multiply the two tensors you created in 3 using **dot product**.
6. Create a tensor with **random values** between 0 and 1 with shape `[224, 224, 3]`.
7. Find the **min** and **max values** of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the **index** which has the **maximum value**.
10. **One-hot** encode the tensor you created in 9.

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.


In [6]:
# Vector
vector = tf.constant([1,2,3])
# Scalar
scalar = tf.constant(4)
# Matrix
matrix = tf.constant([
    [5,6,7],
    [8,9,0]
])
# Tensor
tensor = tf.constant([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]],
])
vector, scalar, matrix, tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 6, 7],
        [8, 9, 0]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

In [47]:
# prompt: Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

import tensorflow as tf

# Vector
vector = tf.constant([10, 20, 30])

# Scalar
scalar = tf.constant(5)

# Matrix
matrix = tf.constant([[1, 2, 3],
                     [4, 5, 6]])

# Tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]])

vector, scalar, matrix, tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

### 2. Find the **shape**, **rank** and **size** of the tensors you created in 1.

In [5]:
print(f'The shape of the tensor: {tensor.shape}')
print(f'The rank of the tensor: {tf.rank(tensor)}')
print(f'The size of the tensor: {tf.size(tensor)}')

The shape of the tensor: (2, 2, 3)
The rank of the tensor: 3
The size of the tensor: 12


### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.


In [16]:
tf.random.set_seed(21)

tensor_1 = tf.random.uniform(shape=(5, 300))
tensor_2 = tf.random.uniform(shape=(5, 300))

tensor_1, tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.02487183, 0.86122084, 0.2314794 , ..., 0.00166988, 0.22818995,
         0.20773864],
        [0.84511733, 0.862326  , 0.22182202, ..., 0.13496447, 0.712358  ,
         0.47099423],
        [0.18548656, 0.35829294, 0.7845197 , ..., 0.33764052, 0.91040885,
         0.6526542 ],
        [0.26283324, 0.650365  , 0.35418415, ..., 0.5402049 , 0.58778334,
         0.7119951 ],
        [0.42069805, 0.7566099 , 0.10385478, ..., 0.41899133, 0.01865804,
         0.1769396 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.53068984, 0.7828057 , 0.62299955, ..., 0.20656443, 0.28336847,
         0.587453  ],
        [0.4731995 , 0.9964341 , 0.06107044, ..., 0.00602686, 0.9677532 ,
         0.0920676 ],
        [0.32565475, 0.06473827, 0.8399373 , ..., 0.62608504, 0.84129286,
         0.5707158 ],
        [0.40476048, 0.3515731 , 0.8599429 , ..., 0.09070528, 0.20379293,
         0.9714831 ],
        [0.50789

### 4. Multiply the two tensors you created in 3 using **matrix multiplication**.


In [21]:
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[69.15886 , 69.081055, 73.96407 , 76.60339 , 76.52305 ],
       [69.07218 , 67.78572 , 73.46926 , 72.86955 , 69.65544 ],
       [75.843056, 71.379654, 80.33463 , 80.130394, 79.26595 ],
       [67.74473 , 68.87235 , 75.23732 , 76.53663 , 71.164566],
       [71.706436, 68.827225, 74.11756 , 71.934135, 70.3908  ]],
      dtype=float32)>

### 5. Multiply the two tensors you created in 3 using **dot product**.


In [23]:
tf.tensordot(tensor_1 , tf.transpose(tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[69.15886 , 69.081055, 73.96407 , 76.60339 , 76.52305 ],
       [69.07218 , 67.78572 , 73.46926 , 72.86955 , 69.65544 ],
       [75.843056, 71.379654, 80.33463 , 80.130394, 79.26595 ],
       [67.74473 , 68.87235 , 75.23732 , 76.53663 , 71.164566],
       [71.706436, 68.827225, 74.11756 , 71.934135, 70.3908  ]],
      dtype=float32)>

### 6. Create a tensor with **random values** between 0 and 1 with shape `[224, 224, 3]`.


In [25]:
big_tensor = tf.random.uniform(shape = [224 , 224 , 3])

big_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.96822417, 0.01625335, 0.523294  ],
        [0.11969995, 0.71787894, 0.38164163],
        [0.88507056, 0.6066896 , 0.346514  ],
        ...,
        [0.3815174 , 0.4330411 , 0.14655244],
        [0.944376  , 0.70168436, 0.32015705],
        [0.6934674 , 0.19192684, 0.8117484 ]],

       [[0.41534853, 0.25270236, 0.7879491 ],
        [0.52618456, 0.1076417 , 0.30879343],
        [0.65554523, 0.55239797, 0.32791388],
        ...,
        [0.31004   , 0.83628404, 0.04243493],
        [0.87515306, 0.77980375, 0.28031528],
        [0.62878823, 0.5550324 , 0.37548482]],

       [[0.7713864 , 0.5092932 , 0.4444313 ],
        [0.9548459 , 0.03707302, 0.39293134],
        [0.2590468 , 0.43399465, 0.1117481 ],
        ...,
        [0.35584795, 0.1524545 , 0.3944292 ],
        [0.9094734 , 0.06423223, 0.36660612],
        [0.03240347, 0.04974902, 0.6391115 ]],

       ...,

       [[0.3044591 , 0.8226719 , 0.15283585],
        [0.36

### 7. Find the **min** and **max values** of the tensor you created in 6.


In [27]:
# Finding the minimum
minimum = tf.math.reduce_min(big_tensor)
print(f'The minimum value is: {minimum}')

The minimum value is: 1.1920928955078125e-07


In [28]:
# Finding the maximum
maximum = tf.math.reduce_max(big_tensor)
print(f'The maximum value is: {maximum}')

The maximum value is: 0.999998927116394


### 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.


In [30]:
unsqueezed_tensor = tf.random.normal(shape = (1 , 224 , 224 , 3))
unsqueezed_tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[ 0.91858834, -0.8988855 ,  1.01962   ],
         [ 0.81367284,  0.85094947,  0.53517884],
         [-1.1424727 ,  1.0905274 , -0.709413  ],
         ...,
         [ 0.43715468,  0.76261926, -1.6712233 ],
         [-0.3059507 ,  1.2130467 ,  0.03390339],
         [ 0.40957218,  0.23454729,  1.1314242 ]],

        [[ 1.0235358 , -1.1438445 ,  1.6651062 ],
         [-0.00998256,  1.5128675 ,  1.7891437 ],
         [ 1.0287277 , -0.6071096 ,  2.2879753 ],
         ...,
         [-1.3873688 ,  0.22559856, -0.8262125 ],
         [ 0.2698663 , -0.39230862,  0.4197788 ],
         [ 0.43295124,  0.07501791, -0.64803815]],

        [[ 0.8581819 ,  1.2272048 , -0.4942438 ],
         [-0.746932  , -1.0385814 ,  0.8728876 ],
         [ 0.35283569, -2.1575239 , -0.7441783 ],
         ...,
         [ 1.5785187 ,  0.9309096 , -0.213405  ],
         [-1.5074198 ,  1.441938  , -1.2501291 ],
         [ 0.68811256,  0.61817753, -0.7054321

In [31]:
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
squeezed_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.91858834, -0.8988855 ,  1.01962   ],
        [ 0.81367284,  0.85094947,  0.53517884],
        [-1.1424727 ,  1.0905274 , -0.709413  ],
        ...,
        [ 0.43715468,  0.76261926, -1.6712233 ],
        [-0.3059507 ,  1.2130467 ,  0.03390339],
        [ 0.40957218,  0.23454729,  1.1314242 ]],

       [[ 1.0235358 , -1.1438445 ,  1.6651062 ],
        [-0.00998256,  1.5128675 ,  1.7891437 ],
        [ 1.0287277 , -0.6071096 ,  2.2879753 ],
        ...,
        [-1.3873688 ,  0.22559856, -0.8262125 ],
        [ 0.2698663 , -0.39230862,  0.4197788 ],
        [ 0.43295124,  0.07501791, -0.64803815]],

       [[ 0.8581819 ,  1.2272048 , -0.4942438 ],
        [-0.746932  , -1.0385814 ,  0.8728876 ],
        [ 0.35283569, -2.1575239 , -0.7441783 ],
        ...,
        [ 1.5785187 ,  0.9309096 , -0.213405  ],
        [-1.5074198 ,  1.441938  , -1.2501291 ],
        [ 0.68811256,  0.61817753, -0.7054321 ]],

       ...,

     

### 9. Create a tensor with shape `[10]` using your own choice of values, then find the **index** which has the **maximum value**.


In [38]:
ten_tensor = tf.constant([0.3631413, 0.03688705, 0.7135688, 0.08872939, 0.60923636, 1.8402596, 0.43164384, 0.403119, 1.1801982, 0.5422273])
max_value = tf.math.argmax(ten_tensor) # it should be 5

print(f'The indices where the value is maximum: {max_value}')
print(f'The maximum value was: {ten_tensor[max_value]}')

The indices where the value is maximum: 5
The maximum value was: 1.8402595520019531


### 10. **One-hot** encode the tensor you created in 9.

In [39]:
i_ten_tensor = tf.cast(ten_tensor * 10, dtype=tf.int32)
i_ten_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 3,  0,  7,  0,  6, 18,  4,  4, 11,  5], dtype=int32)>

In [41]:
tf.one_hot(i_ten_tensor, depth=19)

<tf.Tensor: shape=(10, 19), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]], dtype=float32)>

In [46]:
# prompt: ten_tensor vector 를 one hot encoding 하기

# Assuming ten_tensor is defined as in the provided code
ten_tensor = tf.constant([0.3631413, 0.03688705, 0.7135688, 0.08872939, 0.60923636, 1.8402596, 0.43164384, 0.403119, 1.1801982, 0.5422273])

# Convert ten_tensor to integer type (assuming you want integer indices for one-hot encoding)
i_ten_tensor = tf.cast(ten_tensor * 10, dtype=tf.int32)

# Perform one-hot encoding
one_hot_tensor = tf.one_hot(i_ten_tensor, depth=19)  # Assuming a depth of 19, adjust as needed

one_hot_tensor

<tf.Tensor: shape=(10, 19), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]], dtype=float32)>

In [45]:
# prompt: 0 ~ 1 사이의 숫자 10개를 랜덤하게 생성한 tensor vector 를 one hot encoding 하기

import tensorflow as tf

# 0 ~ 1 사이의 숫자 10개를 랜덤하게 생성한 tensor vector
random_tensor = tf.random.uniform(shape=[10], minval=0, maxval=1)

# One-hot encoding
depth = 10  # 0 ~ 9까지의 값을 one-hot encoding 하기 위한 depth
one_hot_tensor = tf.one_hot(tf.cast(random_tensor * depth, tf.int32), depth=depth)

print("Random Tensor:", random_tensor)
print("One-Hot Encoded Tensor:\n", one_hot_tensor)

Random Tensor: tf.Tensor(
[0.58387744 0.31097937 0.21512985 0.3313203  0.5393467  0.5277004
 0.40084302 0.09395587 0.9640734  0.5168748 ], shape=(10,), dtype=float32)
One-Hot Encoded Tensor:
 tf.Tensor(
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
