## 🛠 Exercises

In [ ]:
import tensorflow as tf

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [ ]:
scalar = tf.constant(5)
vector = tf.constant([1, 2])
matrix = tf.constant([[3, 4], [5, 6]])
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]], dtype=int32)>)

2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:
tf.shape(scalar), tf.rank(scalar), tf.size(scalar)

(<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
tf.shape(vector), tf.rank(vector), tf.size(vector)

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
tf.shape(matrix), tf.rank(matrix), tf.size(matrix)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
tf.shape(tensor), tf.rank(tensor), tf.size(tensor)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [ ]:
tf.random.set_seed(10)
rt1 = tf.random.uniform(shape=[5, 300])
rt2 = tf.random.uniform(shape=[5, 300])
rt1, rt2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.644151  , 0.8082472 , 0.8976548 , ..., 0.64856505, 0.92532265,
         0.21082604],
        [0.3861388 , 0.6250967 , 0.8140892 , ..., 0.4822954 , 0.8364854 ,
         0.02696836],
        [0.01568139, 0.070153  , 0.07581997, ..., 0.03713143, 0.10203564,
         0.9430717 ],
        [0.6311755 , 0.6480881 , 0.02148747, ..., 0.8134506 , 0.1877768 ,
         0.34784198],
        [0.58412063, 0.90507317, 0.08946109, ..., 0.4087528 , 0.11643791,
         0.3630116 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.55478156, 0.42658198, 0.14140713, ..., 0.72380817, 0.6550746 ,
         0.51707363],
        [0.85620296, 0.32831955, 0.8992617 , ..., 0.59535074, 0.19864571,
         0.9972522 ],
        [0.9124336 , 0.4107405 , 0.8301928 , ..., 0.20624447, 0.42023182,
         0.06111217],
        [0.8689436 , 0.80587316, 0.5161364 , ..., 0.870033  , 0.383214  ,
         0.43737292],
        [0.36501

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tf.matmul(rt1, tf.reshape(rt2, shape=(300, 5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[71.80579 , 78.936806, 79.91461 , 78.56192 , 78.249985],
       [74.61162 , 81.50494 , 78.58472 , 78.1964  , 76.19768 ],
       [70.507515, 74.05982 , 75.40812 , 74.66524 , 76.583786],
       [68.26199 , 75.09592 , 68.821465, 70.49203 , 69.1523  ],
       [75.22302 , 85.50049 , 82.40537 , 82.89246 , 78.557144]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.matmul(rt1, tf.transpose(rt2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.69089 , 77.17377 , 70.95266 , 83.92833 , 80.61466 ],
       [74.66354 , 77.68826 , 71.44917 , 84.42623 , 79.83246 ],
       [69.35523 , 74.14987 , 69.53276 , 79.17699 , 76.226944],
       [68.41116 , 72.10269 , 66.07191 , 74.73178 , 73.692085],
       [74.01436 , 80.47031 , 73.773224, 85.81409 , 83.57859 ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [ ]:
rt3 = tf.random.uniform(shape=(224, 224, 3))
rt3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.21397555, 0.2643757 , 0.28710473],
        [0.25718975, 0.52617586, 0.91361344],
        [0.0447216 , 0.10029984, 0.09849989],
        ...,
        [0.58174455, 0.2887715 , 0.5615276 ],
        [0.42705667, 0.64624274, 0.09242129],
        [0.21425843, 0.6151191 , 0.82362616]],

       [[0.9738668 , 0.3125571 , 0.557207  ],
        [0.50410247, 0.5219362 , 0.30598593],
        [0.1761465 , 0.5207732 , 0.4444375 ],
        ...,
        [0.28069592, 0.48089588, 0.5091605 ],
        [0.2821281 , 0.40169716, 0.993888  ],
        [0.97967446, 0.29352677, 0.72037685]],

       [[0.13525677, 0.21918023, 0.49843597],
        [0.7221161 , 0.20129669, 0.83721614],
        [0.24425614, 0.33354807, 0.41158438],
        ...,
        [0.30333376, 0.05302632, 0.28196692],
        [0.2015233 , 0.18005562, 0.72888017],
        [0.03845644, 0.8930398 , 0.55132914]],

       ...,

       [[0.5560229 , 0.5008652 , 0.6037562 ],
        [0.77

7. Find the min and max values of the tensor you created in 6.

In [ ]:
tf.reduce_min(rt3), tf.reduce_max(rt3)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.66893e-06>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999931>)

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [ ]:
tf.squeeze(tf.random.uniform(shape=(1, 224, 224, 3)))

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.36972272, 0.71753395, 0.47393608],
        [0.5105393 , 0.03172052, 0.9922534 ],
        [0.2888118 , 0.5410501 , 0.5243013 ],
        ...,
        [0.0814687 , 0.12145126, 0.6564065 ],
        [0.8112055 , 0.17618   , 0.6871786 ],
        [0.62845075, 0.1272161 , 0.8027468 ]],

       [[0.6930344 , 0.44599724, 0.628914  ],
        [0.3750267 , 0.04310226, 0.89763975],
        [0.09768474, 0.5758071 , 0.2960837 ],
        ...,
        [0.9532541 , 0.18054235, 0.76729536],
        [0.0686326 , 0.5063958 , 0.32386482],
        [0.6551193 , 0.74971604, 0.69964385]],

       [[0.5558903 , 0.7498704 , 0.8201214 ],
        [0.36736226, 0.5536103 , 0.8432181 ],
        [0.11633825, 0.5597563 , 0.6796478 ],
        ...,
        [0.4298005 , 0.82902443, 0.33343232],
        [0.46054077, 0.3107102 , 0.80764616],
        [0.07650483, 0.21793199, 0.68653023]],

       ...,

       [[0.46779907, 0.29490995, 0.11963928],
        [0.17

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [ ]:
import numpy as np
tensor = tf.constant(np.random.randint(0, 100, size=100))
tensor

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([4, 7, 4, 2, 1, 4, 8, 0, 7, 7])>

In [ ]:
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

10. One-hot encode the tensor you created in 9.

In [ ]:
tf.one_hot(tensor, depth=10, dtype=tf.int32)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int32)>