<a href="https://colab.research.google.com/github/cnrywjd11/TensorFlow_for_Deep_Learning_Bootcamp/blob/week1%2Fjwchoi/00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [1]:
import tensorflow as tf

In [9]:
vector = tf.constant([1,2])
scalar = tf.constant(7)
Matrix = tf.constant([[1,2],[3,4]])
Tensor = tf.constant([[[1,2],[3,4]]])

In [10]:
vector, scalar, Matrix, Tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]]], dtype=int32)>)

2. Find the shape, rank and size of the tensors you created in 1.

In [12]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [13]:
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [14]:
Matrix.shape, Matrix.ndim, tf.size(Matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [15]:
Tensor.shape, Tensor.ndim, tf.size(Tensor)

(TensorShape([1, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [19]:
T1 = tf.random.Generator.from_seed(100).normal(shape=(5, 300))
T2 =tf.random.Generator.from_seed(101).normal(shape=(5, 300))

In [20]:
T1, T2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.90112925, -0.0175216 , -0.4188493 , ..., -0.4321791 ,
          1.1739746 ,  0.34979692],
        [-0.3643946 , -3.1925747 ,  0.74550235, ...,  0.84823394,
         -0.25278994,  1.9206251 ],
        [ 0.28755897, -0.5995689 , -0.96432054, ..., -0.8950815 ,
          1.3879406 ,  0.9307403 ],
        [-0.1455882 ,  0.47244102, -0.6284949 , ...,  0.44786277,
          0.7897152 , -1.1668082 ],
        [ 1.4570636 , -0.06070056,  0.32132152, ..., -0.06993853,
          0.9464174 , -1.1680335 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[ 0.08036723, -1.7199678 , -0.6891769 , ..., -3.1925747 ,
          0.74550235,  1.6823604 ],
        [ 1.0547173 ,  0.43973717, -1.5463331 , ..., -0.5995689 ,
         -0.96432054,  0.2030316 ],
        [-0.47879514, -0.673436  ,  1.2044759 , ...,  0.47244102,
         -0.6284949 ,  0.38839826],
        [ 1.8276811 , -0.32110527,  0.66303664, ..., -0.06070056

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [22]:
tf.matmul(T1,tf.reshape(T2, shape=(300, 5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 13.07712   ,   5.7567916 ,  19.574226  ,  -1.0552359 ,
        -32.583282  ],
       [ -7.1636405 ,  15.051571  , -15.870622  , -17.011593  ,
         -7.990184  ],
       [  6.119339  ,  -0.11221433,   1.2579386 ,   5.979478  ,
        -40.37672   ],
       [ 25.240788  ,  10.606144  , -18.27661   , -23.603588  ,
         22.708105  ],
       [  2.1643357 , -21.203434  , -35.481903  ,  -6.701633  ,
         -6.5635223 ]], dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [23]:
tf.tensordot(tf.transpose(T1), T2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[ 1.0970044 ,  0.6822003 , -0.07147767, ...,  5.05513   ,
        -1.097817  , -1.6931857 ],
       [-2.2996793 , -1.0983362 ,  4.6026707 , ...,  1.5825557 ,
         3.6171434 , -1.3033327 ],
       [ 0.49734393,  1.7758324 , -2.774423  , ...,  0.8730571 ,
        -0.7483037 , -0.46148327],
       ...,
       [ 2.0130641 ,  1.6022103 , -1.7226803 , ...,  0.33400956,
        -0.40730256, -1.2719715 ],
       [ 1.8780242 , -3.6827433 ,  0.7990871 , ..., -1.809719  ,
         0.14322555,  1.5615064 ],
       [-2.0935833 ,  0.44017908, -1.6564636 , ..., -3.2127512 ,
        -2.110386  ,  2.6178088 ]], dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [24]:
T3 = tf.random.Generator.from_seed(100).normal(shape=(224, 224, 3))

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [25]:
tf.reduce_min(T3), tf.reduce_max(T3)

(<tf.Tensor: shape=(), dtype=float32, numpy=-4.848316>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.4032865>)

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [26]:
T4 = tf.random.Generator.from_seed(100).normal(shape=(1, 224, 224, 3))
T4_squeezed = tf.squeeze(T4)
T4, T4_squeezed

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[-0.90112925, -0.0175216 , -0.4188493 ],
          [ 0.29532313,  0.08036723, -1.7199678 ],
          [-0.6891769 ,  0.22862972, -0.69891334],
          ...,
          [ 0.52378887,  0.98307234,  0.34288085],
          [ 1.216793  , -1.24293   ,  0.84324265],
          [-0.23379943,  0.4276398 , -1.0215694 ]],
 
         [[-1.4299808 ,  0.19492291, -0.10816212],
          [ 0.8752192 ,  0.02671668,  0.76397264],
          [ 1.222406  ,  0.46577054,  0.22190082],
          ...,
          [ 1.4884479 ,  0.33970562,  2.2447717 ],
          [-0.46612498, -0.9905671 ,  1.6669905 ],
          [-1.348683  , -0.9285897 ,  0.64070654]],
 
         [[-1.1137408 ,  1.2421573 , -1.0235466 ],
          [-0.57331395,  1.60733   , -0.5550322 ],
          [ 0.3821156 ,  0.8475615 , -0.18030316],
          ...,
          [-1.4313707 ,  0.31060782,  0.11755535],
          [ 0.47162578,  0.1313885 ,  0.6719677 ],
          [-1.753269  ,

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [30]:
import numpy as np
T5 = tf.constant(np.arange(1, 11, dtype=np.int32))
tf.argmax(T5)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

10. One-hot encode the tensor you created in 9.

In [31]:
tf.one_hot(T5, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>