## 🛠 Exercises

In [1]:
import tensorflow as tf
import numpy as np

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [2]:
# vector
vector = tf.constant(tf.ones((10, )), dtype=tf.float32)
vector

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [3]:
# scalar
scalar = tf.constant(10, dtype=tf.float32)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [4]:
# matrix
matrix = tf.constant(tf.ones((10, 10, )), dtype=tf.float32)
matrix

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [5]:
# tensor
tensor = tf.constant(tf.ones((10, 10, 10, )), dtype=tf.float32)
tensor

<tf.Tensor: shape=(10, 10, 10), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.,

2. Find the shape, rank and size of the tensors you created in 1.

In [6]:
print(tf.shape(vector), tf.rank(vector), tf.size(vector))

tf.Tensor([10], shape=(1,), dtype=int32) tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(10, shape=(), dtype=int32)


In [7]:
print(tf.shape(scalar), tf.rank(scalar), tf.size(scalar))

tf.Tensor([], shape=(0,), dtype=int32) tf.Tensor(0, shape=(), dtype=int32) tf.Tensor(1, shape=(), dtype=int32)


In [8]:
print(tf.shape(matrix), tf.rank(matrix), tf.size(matrix))

tf.Tensor([10 10], shape=(2,), dtype=int32) tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(100, shape=(), dtype=int32)


In [9]:
print(tf.shape(tensor), tf.rank(tensor), tf.size(tensor))

tf.Tensor([10 10 10], shape=(3,), dtype=int32) tf.Tensor(3, shape=(), dtype=int32) tf.Tensor(1000, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [10]:
tensor1 = tf.constant(np.random.random((5, 300)))
tensor2 = tf.constant(np.random.random((5, 300)))

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [11]:
tf.matmul(tf.transpose(tensor1), tensor2)

<tf.Tensor: shape=(300, 300), dtype=float64, numpy=
array([[1.32067405, 1.3192073 , 1.32220483, ..., 1.9973551 , 1.32517774,
        1.98672023],
       [1.19508218, 0.78350027, 2.16553149, ..., 1.92681365, 1.68294644,
        1.55521073],
       [1.17762973, 0.91775383, 1.1123962 , ..., 1.25471314, 0.87824912,
        0.96145426],
       ...,
       [1.72237685, 1.51761679, 1.86321345, ..., 2.35306705, 1.64221451,
        2.24986537],
       [1.30071871, 0.88549658, 1.73241487, ..., 1.59057514, 1.24422498,
        1.59556689],
       [0.91596282, 0.87730677, 1.20345404, ..., 1.74685837, 1.29472071,
        1.4163811 ]])>

5. Multiply the two tensors you created in 3 using dot product.

In [12]:
tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float64, numpy=
array([[1.32067405, 1.3192073 , 1.32220483, ..., 1.9973551 , 1.32517774,
        1.98672023],
       [1.19508218, 0.78350027, 2.16553149, ..., 1.92681365, 1.68294644,
        1.55521073],
       [1.17762973, 0.91775383, 1.1123962 , ..., 1.25471314, 0.87824912,
        0.96145426],
       ...,
       [1.72237685, 1.51761679, 1.86321345, ..., 2.35306705, 1.64221451,
        2.24986537],
       [1.30071871, 0.88549658, 1.73241487, ..., 1.59057514, 1.24422498,
        1.59556689],
       [0.91596282, 0.87730677, 1.20345404, ..., 1.74685837, 1.29472071,
        1.4163811 ]])>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [13]:
tensor1 = tf.constant(np.random.random((224, 224, 3)))

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [14]:
print(tf.reduce_min(tensor1, axis=1), tf.reduce_max(tensor1, axis=1))

tf.Tensor(
[[7.96068875e-04 6.39274394e-03 2.94416445e-03]
 [2.27657560e-03 1.75830778e-04 1.23606508e-02]
 [2.54912802e-03 5.09931865e-03 1.86876048e-03]
 [3.36438078e-03 2.05587913e-03 1.10517864e-03]
 [2.49664385e-03 1.86291638e-02 7.64180189e-03]
 [1.48314464e-03 2.48356218e-02 6.81699440e-04]
 [1.07742203e-02 2.55886053e-03 3.03571750e-03]
 [1.06788468e-02 1.37648805e-02 1.21017835e-02]
 [1.47535966e-03 2.05920932e-02 1.52178431e-02]
 [2.43130022e-03 1.40182671e-04 5.64960974e-04]
 [1.16688114e-03 2.50239623e-03 4.92286670e-03]
 [3.16360650e-03 1.61122153e-03 4.52716619e-03]
 [2.54812823e-03 1.85060802e-03 4.69552510e-04]
 [8.88936576e-04 1.59599090e-02 6.23238839e-04]
 [7.63669937e-03 3.32724028e-03 3.04623677e-03]
 [8.57638046e-04 2.01314179e-04 6.59218719e-03]
 [1.81722882e-02 1.91296253e-03 7.32189722e-03]
 [2.02078107e-03 2.26850608e-03 1.20167030e-03]
 [7.34178379e-03 2.99650850e-03 1.78380143e-03]
 [9.42667409e-04 3.83864737e-03 7.09230246e-03]
 [2.74187047e-02 5.06881510e-

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [15]:
tensor2 = tensor1[tf.newaxis, ...]
tensor2.shape

TensorShape([1, 224, 224, 3])

In [16]:
tensor3 = tf.squeeze(tensor2)
tensor3.shape

TensorShape([224, 224, 3])

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [17]:
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tf.argmax(tensor1)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

10. One-hot encode the tensor you created in 9.

In [18]:
tf.one_hot(tensor1, 11)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

## 📖 Extra-curriculum

* Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?
* Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
* Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.

### 1

In [19]:
# tf.math.exp
# Computes exponential of x element-wise. y = e^x
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=tf.float32)
tf.exp(tensor1)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 2.0085537e+01, 5.4598148e+01,
       1.4841316e+02, 4.0342877e+02, 1.0966332e+03, 2.9809578e+03,
       8.1030840e+03, 2.2026465e+04], dtype=float32)>

### 2

In [20]:
@tf.function
def tf_function(grocery_bill):
  return tf.reduce_sum(grocery_bill)

grocery_bill = tf.constant([
    1000,
    2000,
    3000
])

tf_function(grocery_bill)

<tf.Tensor: shape=(), dtype=int32, numpy=6000>

### 3

In [21]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [22]:
import requests
requests.packages.urllib3.disable_warnings()
import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

In [23]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [24]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

/Users/user/Projects/ds-conversion-trainer/venv/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [25]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.0891747 , 0.07081223, 0.07387353, 0.07827519, 0.2109218 ,
        0.10178584, 0.06799731, 0.09378825, 0.10466479, 0.10870638]],
      dtype=float32)

In [26]:
tf.nn.softmax(predictions).numpy()

array([[0.09884409, 0.09704563, 0.09734317, 0.09777258, 0.11164127,
        0.10009851, 0.09677283, 0.09930116, 0.10038711, 0.10079366]],
      dtype=float32)

In [27]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [28]:
loss_fn(y_train[:1], predictions).numpy()

2.3016005

In [29]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [30]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/Users/user/Projects/ds-conversion-trainer/venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:635: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8614 - loss: 0.4761
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9575 - loss: 0.1477
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9679 - loss: 0.1048
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9733 - loss: 0.0904
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9781 - loss: 0.0704


In [31]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9804 - loss: 0.0607
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9830 - loss: 0.0544
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9843 - loss: 0.0510
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 971us/step - accuracy: 0.9856 - loss: 0.0447
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9867 - loss: 0.0424
313/313 - 0s - 471us/step - accuracy: 0.9809 - loss: 0.0675


[0.06746485084295273, 0.98089998960495]

In [32]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [33]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533692, 0.08533692, 0.08533692, 0.08533776, 0.08533692,
        0.08533692, 0.08533692, 0.23196663, 0.08533692, 0.08533726],
       [0.08533674, 0.08533676, 0.2319693 , 0.08533674, 0.08533674,
        0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674],
       [0.08533956, 0.23192476, 0.08534631, 0.08533957, 0.08534051,
        0.08533957, 0.08533963, 0.08535009, 0.08534047, 0.08533956],
       [0.23196684, 0.0853369 , 0.08533753, 0.0853369 , 0.0853369 ,
        0.0853369 , 0.0853369 , 0.0853369 , 0.0853369 , 0.08533733],
       [0.08539713, 0.08539711, 0.08539718, 0.08539711, 0.2310112 ,
        0.08539711, 0.08539712, 0.08539749, 0.08539711, 0.08581147]],
      dtype=float32)>