## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [88]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [89]:
# Ex1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

vector = tf.constant([1,2,3])
scalar = tf.constant(1)
matrix = tf.constant([[1,2,3],[4,5,6]]) 
tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]]) 
vector, scalar, matrix, tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=int32)>)

In [90]:
# Ex2. Find the shape, rank and size of the tensors you created in 1.
print("vector : shape={}, rank={}, size={}".format(vector.shape, vector.ndim, tf.size(vector)))
print("scalar : shape={}, rank={}, size={}".format(scalar.shape, scalar.ndim, tf.size(scalar)))
print("matrix : shape={}, rank={}, size={}".format(matrix.shape, matrix.ndim, tf.size(matrix)))
print("tensor : shape={}, rank={}, size={}".format(tensor.shape, tensor.ndim, tf.size(tensor)))

vector : shape=(3,), rank=1, size=3
scalar : shape=(), rank=0, size=1
matrix : shape=(2, 3), rank=2, size=6
tensor : shape=(1, 3, 3), rank=3, size=9


In [91]:
# Ex3.  Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
random_A = tf.random.uniform(shape=(5,300))
random_B = tf.random.uniform(shape=(5,300))
print(random_A)
print(random_B)


tf.Tensor(
[[0.5893128  0.6692287  0.9299928  ... 0.90287685 0.45422924 0.89077914]
 [0.00923467 0.659773   0.57638216 ... 0.20906639 0.9899533  0.8566638 ]
 [0.23230481 0.49630272 0.8980428  ... 0.08721006 0.10718763 0.56374717]
 [0.44347322 0.77050567 0.92604816 ... 0.97330976 0.64605796 0.39562535]
 [0.16618788 0.5874078  0.7500695  ... 0.08091617 0.19793499 0.75361073]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.3022319  0.08976114 0.8714596  ... 0.47746432 0.3916105  0.76375437]
 [0.13422    0.7804123  0.4892559  ... 0.79014087 0.9841311  0.91196096]
 [0.8515804  0.05416965 0.25891745 ... 0.823266   0.0722208  0.84859776]
 [0.8546076  0.62253225 0.23044252 ... 0.29979622 0.94119346 0.5575299 ]
 [0.43089807 0.03513896 0.6113281  ... 0.52724946 0.5899949  0.63132286]], shape=(5, 300), dtype=float32)


In [92]:
# Ex4. Multiply the two tensors you created in 3 using matrix multiplication.
result = tf.transpose(random_A) @ random_B
print(result)

tf.Tensor(
[[0.8277804  0.35460415 0.78201854 ... 0.70049524 0.77209055 1.0078131 ]
 [1.6250515  1.1021558  1.5711612  ... 1.7901407  2.018986   2.334399  ]
 [2.2378025  1.1847912  1.9969078  ... 2.3118892  2.3104155  2.9878368 ]
 ...
 [1.2418699  0.85768545 1.1854463  ... 1.0025381  1.529436   1.5479764 ]
 [0.9988488  1.2282974  1.1778182  ... 1.3853716  1.8847121  1.825835  ]
 [1.5271132  1.0518169  1.8932422  ... 2.0822623  2.0496087  2.6363196 ]], shape=(300, 300), dtype=float32)


In [93]:
# Ex5. Multiply the two tensors you created in 3 using dot product.
print(tf.tensordot(tf.transpose(random_A), random_B, axes=1))

tf.Tensor(
[[0.8277804  0.35460415 0.78201854 ... 0.70049524 0.77209055 1.0078131 ]
 [1.6250515  1.1021558  1.5711612  ... 1.7901407  2.018986   2.334399  ]
 [2.2378025  1.1847912  1.9969078  ... 2.3118892  2.3104155  2.9878368 ]
 ...
 [1.2418699  0.85768545 1.1854463  ... 1.0025381  1.529436   1.5479764 ]
 [0.9988488  1.2282974  1.1778182  ... 1.3853716  1.8847121  1.825835  ]
 [1.5271132  1.0518169  1.8932422  ... 2.0822623  2.0496087  2.6363196 ]], shape=(300, 300), dtype=float32)


In [94]:
# Ex6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
X = tf.random.uniform(shape=(224,224,3))
print(X)

tf.Tensor(
[[[0.07358789 0.2588451  0.18218756]
  [0.8745556  0.75599146 0.05744505]
  [0.50118876 0.4064839  0.03880084]
  ...
  [0.10998988 0.23147237 0.9333668 ]
  [0.6109834  0.08130777 0.85861003]
  [0.97268856 0.8966025  0.75130475]]

 [[0.80272293 0.12704408 0.4282341 ]
  [0.03104496 0.54290164 0.45967555]
  [0.5206237  0.47682142 0.8821484 ]
  ...
  [0.25090063 0.3799522  0.63695204]
  [0.2640816  0.5584042  0.9748882 ]
  [0.33006573 0.80493915 0.8801452 ]]

 [[0.19801426 0.46255958 0.7001802 ]
  [0.857522   0.4342295  0.5901879 ]
  [0.74551857 0.11027002 0.777591  ]
  ...
  [0.8525878  0.8223703  0.17134285]
  [0.85608745 0.66945124 0.8216547 ]
  [0.17041743 0.74995005 0.36016762]]

 ...

 [[0.7225884  0.9134724  0.1757425 ]
  [0.24075866 0.5682757  0.777187  ]
  [0.0708226  0.39296925 0.6441128 ]
  ...
  [0.27701354 0.46480036 0.16744542]
  [0.18899548 0.6075649  0.3345909 ]
  [0.05338407 0.7872944  0.22828937]]

 [[0.8456279  0.10470009 0.79802215]
  [0.4103551  0.31276286 0

In [95]:
# ex7. Find the min and max values of the tensor you created in 6.
print(tf.reduce_min(X), tf.reduce_max(X))

tf.Tensor(2.4318695e-05, shape=(), dtype=float32) tf.Tensor(0.9999963, shape=(), dtype=float32)


In [96]:
# ex8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
X = tf.random.normal(shape=(1,224,224,3))
print(X)
print(tf.squeeze(X))

tf.Tensor(
[[[[-0.3447795   0.01134729 -0.64288783]
   [-2.1654313  -1.0762575   0.18496841]
   [-0.08352145 -0.17109631  1.7821501 ]
   ...
   [-0.7247938   1.9895786   0.16555233]
   [ 0.89161336  0.52467114 -0.9220905 ]
   [ 0.11139641  0.543149   -0.2169276 ]]

  [[ 1.1613967  -0.96895444 -1.3096296 ]
   [-0.82528466 -0.31831208  0.5825781 ]
   [ 0.10964222  1.436453   -0.13969795]
   ...
   [ 1.1701063   1.0252632   0.9437294 ]
   [-0.3836721   2.0514092  -1.5913715 ]
   [-1.0882277  -0.18117964 -1.2636604 ]]

  [[ 1.2968316  -0.63428885 -1.0311545 ]
   [-0.42181966  0.30982468  0.19295134]
   [ 0.8016752  -0.4250102   0.10741065]
   ...
   [ 1.7622242   0.9554785  -0.15234247]
   [-0.35658216 -1.8776987   0.32245907]
   [ 0.04620134  0.740301    0.3483297 ]]

  ...

  [[ 1.1117233  -1.0917101  -0.45776898]
   [ 0.73657185 -0.11248499  1.0506275 ]
   [ 1.0612043   0.33143088  1.9379932 ]
   ...
   [-1.4373571  -0.33333734  0.929391  ]
   [-2.7703264   2.0956905  -1.1263777 ]
   [-

In [97]:
# ex9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
X = tf.random.uniform(shape=(10,), minval=0, maxval=10, dtype=tf.int32)
print(X)
print(tf.argmax(X))

tf.Tensor([7 5 2 6 1 5 1 2 5 1], shape=(10,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int64)


In [98]:
# ex10. One-hot encode the tensor you created in 9.
tf.one_hot(X, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>