In [4]:
import tensorflow as tf

print(tf.__version__)

2.16.2


In [5]:
scalar = tf.constant(7)
scalar

2024-11-13 01:17:31.200052: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2024-11-13 01:17:31.200078: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-11-13 01:17:31.200085: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-11-13 01:17:31.200135: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-11-13 01:17:31.200149: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim

0

In [7]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
tensor = tf.constant([[[1, 2, 3,], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

In [15]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
# changeable_tensor[0] = 7
# changeable_tensor

In [17]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

In [19]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240397 ,  0.28785658],
        [-0.87579006, -0.08856997],
        [ 0.6921164 ,  0.842157  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240397 ,  0.28785658],
        [-0.87579006, -0.08856997],
        [ 0.6921164 ,  0.842157  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [20]:
 not_shuffled = tf.constant([[10, 7], [3,4], [2,5]])
 tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [21]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
tf.random.set_seed(42)
display(tf.random.shuffle(not_shuffled, seed=42))
display(tf.random.shuffle(not_shuffled, seed=42))
display(tf.random.shuffle(not_shuffled, seed=42))


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [23]:
tf.random.set_seed(42)
display(tf.random.shuffle(not_shuffled))
display(tf.random.shuffle(not_shuffled))
display(tf.random.shuffle(not_shuffled))
display(tf.random.shuffle(not_shuffled, seed=1))
display(tf.random.shuffle(not_shuffled, seed=1))
display(tf.random.shuffle(not_shuffled, seed=1))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [24]:
display(tf.random.shuffle(not_shuffled))
display(tf.random.shuffle(not_shuffled))
display(tf.random.shuffle(not_shuffled))
display(tf.random.shuffle(not_shuffled, seed=1))
display(tf.random.shuffle(not_shuffled, seed=1))
display(tf.random.shuffle(not_shuffled, seed=1))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [25]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [27]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [29]:
A.ndim

2

In [30]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
2*3*4*5

120

In [34]:
print(rank_4_tensor.dtype)
print(rank_4_tensor.ndim)
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(rank_4_tensor.shape[-1])
print(tf.size(rank_4_tensor))
print(tf.size(rank_4_tensor).numpy())

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
tf.Tensor(120, shape=(), dtype=int32)
120


In [35]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [36]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
rank_4_tensor[:1, :, :1, :].shape

TensorShape([1, 3, 1, 5])

In [38]:
rank_2_tensor = tf.constant([[10,7], [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [39]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [40]:
print(rank_2_tensor[:, :, tf.newaxis])
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

tf.Tensor(
[[[10]
  [ 7]]

 [[ 3]
  [ 4]]], shape=(2, 2, 1), dtype=int32)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
print(tf.expand_dims(rank_2_tensor, axis=-1))
print(tf.expand_dims(rank_2_tensor, axis=0))

tf.Tensor(
[[[10]
  [ 7]]

 [[ 3]
  [ 4]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[10  7]
  [ 3  4]]], shape=(1, 2, 2), dtype=int32)


In [42]:
tensor = tf.constant([[10, 7], [3,4]])
print(tensor + 10)
print(tensor)
print(tensor * 10)
print(tensor - 10)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)


In [43]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [44]:
import  timeit

large_t = tf.random.normal(shape=(100, 25, 75, 30))

def f1():
 # return large_t * 10
 return large_t / 10

def f2():
 return tf.divide(large_t, 10)

@tf.function
def f3():
 return tf.divide(large_t, 10)

t1 = timeit.timeit(f1, number=5000)
t2 = timeit.timeit(f2, number=5000)
t3 = timeit.timeit(f3, number=5000)
print(t1, t2, t3)

2024-11-13 01:17:35.365881: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1.2752467080000045 1.4093965409999996 1.3453458750000067


In [45]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [46]:
print(tensor)
print(tensor * tensor)
print(tensor @ tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  49]
 [  9  16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [91]:
print(timeit.timeit(lambda: tensor @ tensor, number=100000))
print(timeit.timeit(lambda: tf.matmul(tensor, tensor), number=100000))

5.524238499999996
4.559615082999997


In [48]:
X = tf.constant([[1,2], [3,4], [5,6]])
Y = tf.constant([[7,8], [9,10], [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [49]:
print(tf.matmul(X, Y, transpose_a=True))
print(tf.matmul(X, Y, transpose_b=True))

tf.Tensor(
[[ 89  98]
 [116 128]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)


In [50]:
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [90]:
print(timeit.timeit(lambda: tf.matmul(X,tf.transpose(Y)), number=10000))
print(timeit.timeit(lambda: tf.matmul(X,Y, transpose_b=True), number=10000))
print(timeit.timeit(lambda: tf.tensordot(X, tf.transpose(Y), axes=1), number=10000))

5.380578374999999
0.15468083300000046
5.2988882500000045


In [52]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [53]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [54]:
tf.__version__

'2.16.2'

In [55]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [56]:
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [57]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [58]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [59]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [60]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([88, 44,  7, 81, 83, 29, 61, 28,  3, 13, 51, 94,  1, 80, 33, 21, 62,
       83, 90, 52, 66, 88,  0,  1, 55, 78, 27, 82, 51, 34, 21, 85, 51, 16,
       55, 69, 66,  9, 31, 85, 51, 71, 81, 93, 39, 86, 17, 82, 94, 15])>

In [61]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [62]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [63]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=94>

In [64]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [65]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2603>

In [66]:
EE = tf.cast(E, dtype=tf.float32)
print(tf.reduce_mean(tf.pow(EE - tf.reduce_mean(EE), 2)))
print(tf.sqrt(tf.reduce_mean(tf.pow(EE - tf.reduce_mean(EE), 2))))

print(tf.math.reduce_variance(EE))
print(tf.math.reduce_std(EE))

tf.Tensor(905.8164, shape=(), dtype=float32)
tf.Tensor(30.096785, shape=(), dtype=float32)
tf.Tensor(905.8164, shape=(), dtype=float32)
tf.Tensor(30.096785, shape=(), dtype=float32)


In [67]:
def my_var():
 return tf.reduce_mean(tf.pow(EE - tf.reduce_mean(EE), 2))

def my_std():
 return tf.sqrt(tf.reduce_mean(tf.pow(EE - tf.reduce_mean(EE), 2)))

print(timeit.timeit(my_var, number=10000))
print(timeit.timeit(lambda:tf.math.reduce_variance(EE), number=10000))
print(timeit.timeit(my_std, number=10000))
print(timeit.timeit(lambda:tf.math.reduce_std(EE), number=10000))

1.4643813340000023
1.4696722500000021
1.7416080409999921
1.739838375000005


In [68]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [69]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [70]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [71]:
print(F[tf.argmin(F)])
print(tf.reduce_min(F))

tf.Tensor(0.009463668, shape=(), dtype=float32)
tf.Tensor(0.009463668, shape=(), dtype=float32)


In [72]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [73]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [74]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [75]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [76]:
tf.one_hot(some_list, depth=len(some_list), on_value="123", off_value="456")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'123', b'456', b'456', b'456'],
       [b'456', b'123', b'456', b'456'],
       [b'456', b'456', b'123', b'456'],
       [b'456', b'456', b'456', b'123']], dtype=object)>

In [77]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [78]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [79]:
tf.sqrt(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [80]:
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [81]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [82]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [83]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [84]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [85]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [2]:
import tensorflow as tf
tf.config.list_physical_devices()

/Users/user/PycharmProjects/TensorFlow_for_Deep_Learning_Bootcamp/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [87]:
tf.__version__

'2.16.2'

In [88]:
!pip install tensorflow-macos

In [89]:
!pip install tensorflow-metal

In [4]:
scalar = tf.constant(1.)
vector = tf.constant([1., 2.])
matrix = tf.constant([[1., 2.],[3., 4.]])
tensor = tf.constant(tf.random.uniform(shape=(3, 4, 5)))

In [6]:
def print_2(sample):
 print(sample.shape, sample.ndim, tf.size(sample))
 
print_2(scalar)
print_2(vector)
print_2(matrix)
print_2(tensor)

() 0 tf.Tensor(1, shape=(), dtype=int32)
(2,) 1 tf.Tensor(2, shape=(), dtype=int32)
(2, 2) 2 tf.Tensor(4, shape=(), dtype=int32)
(3, 4, 5) 3 tf.Tensor(60, shape=(), dtype=int32)


In [11]:
t1 = tf.random.uniform((5, 300), 0, 1)
t2 = tf.random.uniform((5, 300), 0, 1)

In [13]:
tf.matmul(t1, t2, transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 98.34755 ,  80.0121  ,  76.37611 ,  70.609406,  74.27988 ],
       [ 80.0121  , 107.65361 ,  74.474396,  72.36779 ,  79.742485],
       [ 76.37611 ,  74.474396,  99.23935 ,  71.1331  ,  72.19905 ],
       [ 70.609406,  72.36779 ,  71.1331  ,  89.66724 ,  69.214325],
       [ 74.27988 ,  79.742485,  72.19905 ,  69.214325,  99.42442 ]],
      dtype=float32)>

In [15]:
tf.tensordot(t1, tf.transpose(t2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 98.34755 ,  80.0121  ,  76.37611 ,  70.609406,  74.27988 ],
       [ 80.0121  , 107.65361 ,  74.474396,  72.36779 ,  79.742485],
       [ 76.37611 ,  74.474396,  99.23935 ,  71.1331  ,  72.19905 ],
       [ 70.609406,  72.36779 ,  71.1331  ,  89.66724 ,  69.214325],
       [ 74.27988 ,  79.742485,  72.19905 ,  69.214325,  99.42442 ]],
      dtype=float32)>

In [16]:
t6 = tf.random.uniform((224, 224, 3), 0, 1)

In [18]:
print(tf.reduce_min(t6))
print(tf.reduce_max(t6))

tf.Tensor(4.053116e-06, shape=(), dtype=float32)
tf.Tensor(0.99998736, shape=(), dtype=float32)


In [19]:
t8 = tf.random.uniform((1,224,224,3), 0, 1)
print(tf.squeeze(t8))

tf.Tensor(
[[[0.31179297 0.8263413  0.6849456 ]
  [0.0067091  0.78749514 0.3906511 ]
  [0.29263055 0.99216926 0.95810425]
  ...
  [0.43970728 0.976676   0.8946736 ]
  [0.9747398  0.7011992  0.73613393]
  [0.4360633  0.7536833  0.01353109]]

 [[0.2823602  0.0927937  0.2424469 ]
  [0.92214036 0.1318667  0.18895125]
  [0.13469017 0.29916108 0.22880554]
  ...
  [0.10263181 0.3771491  0.7380618 ]
  [0.6484846  0.69211054 0.67284966]
  [0.43589175 0.48166    0.14082742]]

 [[0.41235518 0.45162737 0.6804353 ]
  [0.04887676 0.6775023  0.29143417]
  [0.3466624  0.17450547 0.38451958]
  ...
  [0.8667455  0.16113937 0.67500424]
  [0.8560462  0.48929954 0.97561824]
  [0.5725883  0.8036673  0.3923154 ]]

 ...

 [[0.68855166 0.3706571  0.03126299]
  [0.61133444 0.21750414 0.9080095 ]
  [0.20064199 0.31340492 0.85072494]
  ...
  [0.8053781  0.54289234 0.08450699]
  [0.6037886  0.0091573  0.14664805]
  [0.36727667 0.66913784 0.9003469 ]]

 [[0.4256966  0.88771296 0.6295724 ]
  [0.99141705 0.49446368 0

In [20]:
t9 = tf.constant([1,2,3,4,5,6,7,8,9,10])
print(tf.argmax(t9))

tf.Tensor(9, shape=(), dtype=int64)


In [21]:
tf.one_hot(t9, len(t9))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

https://www.tensorflow.org/api_docs/python/tf/einsum

In [66]:
import timeit

X = tf.random.normal((2,3))
Y = tf.random.normal((2,3))

print(tf.matmul(X,tf.transpose(Y)))
print(tf.matmul(X,Y, transpose_b=True))
print(tf.tensordot(X, tf.transpose(Y), axes=1))
print(tf.einsum('ik,jk->ij', X, Y))

print(timeit.timeit(lambda: tf.matmul(X,tf.transpose(Y)), number=10000))
print(timeit.timeit(lambda: tf.matmul(X,Y, transpose_b=True), number=10000))
print(timeit.timeit(lambda: tf.tensordot(X, tf.transpose(Y), axes=1), number=10000))
print(timeit.timeit(lambda: tf.einsum('ik,jk->ij', X, Y), number=10000))

tf.Tensor(
[[ 2.3321762  -0.88794357]
 [-0.88794357  1.2332839 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 2.3321762  -0.88794357]
 [-0.88794357  1.2332839 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 2.3321762  -0.88794357]
 [-0.88794357  1.2332839 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 2.3321762 -0.8879435]
 [-0.8879435  1.2332839]], shape=(2, 2), dtype=float32)
0.9327361669998027
0.3919327080002404
1.370832457999768
0.1666867080002703


In [67]:
A = tf.random.normal((2,3,5))
B = tf.random.normal((2,3,5))

print(tf.matmul(A, B, transpose_b=True))
print(tf.einsum('bik,bjk->bij',A, B))

print(timeit.timeit(lambda: tf.matmul(A, B, transpose_b=True), number=10000))
print(timeit.timeit(lambda: tf.einsum('bik,bjk->bij',A, B), number=10000))

tf.Tensor(
[[[ 3.2798784   0.51854265 -2.786354  ]
  [ 0.51854265  2.828868   -1.3231732 ]
  [-2.786354   -1.3231732   7.6572614 ]]

 [[ 4.5611253  -2.0525615  -0.27128035]
  [-2.0525615   5.481697   -3.3955414 ]
  [-0.27128035 -3.3955414   3.4017682 ]]], shape=(2, 3, 3), dtype=float32)
tf.Tensor(
[[[ 3.2798781   0.5185426  -2.786354  ]
  [ 0.5185426   2.828868   -1.3231733 ]
  [-2.786354   -1.3231733   7.6572614 ]]

 [[ 4.5611253  -2.0525618  -0.27128035]
  [-2.0525618   5.481697   -3.3955417 ]
  [-0.27128035 -3.3955417   3.4017682 ]]], shape=(2, 3, 3), dtype=float32)
0.4083901250000963
0.16653825000003053


In [82]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [83]:
model = tf.keras.models.Sequential([
 tf.keras.layers.Flatten(input_shape=(28, 28)),
 tf.keras.layers.Dense(128, activation='relu'),
 tf.keras.layers.Dropout(0.2),
 tf.keras.layers.Dense(10)
])

/Users/user/PycharmProjects/TensorFlow_for_Deep_Learning_Bootcamp/venv/lib/python3.9/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [85]:
predictions = model(x_train[:1]).numpy()

In [86]:
predictions

array([[ 0.4359669 ,  0.12342291,  0.2785663 , -0.77384734,  0.3951696 ,
         0.8109244 , -0.20347536, -0.48026335, -0.11645067,  0.1171076 ]],
      dtype=float32)

In [89]:
tf.nn.softmax(predictions).numpy()

array([[0.13281453, 0.09716492, 0.11347165, 0.03961229, 0.12750511,
        0.19323581, 0.07007117, 0.05312903, 0.07644229, 0.09655323]],
      dtype=float32)

In [91]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [92]:
loss_fn(y_train[:1], predictions).numpy()

1.643844

In [93]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [94]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2024-11-13 02:20:00.883639: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.8608 - loss: 0.4794
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9557 - loss: 0.1509
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9669 - loss: 0.1072
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9733 - loss: 0.0887
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.9764 - loss: 0.0755


In [95]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.9785 - loss: 0.0703


[0.07030155509710312, 0.9785000085830688]

In [96]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [97]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.90538035e-09, 5.29668087e-09, 2.17116917e-06, 5.64872935e-05,
        3.65498430e-12, 1.21981009e-06, 1.18167113e-13, 9.99932647e-01,
        9.93368303e-07, 6.35612969e-06],
       [1.31168396e-10, 3.72042778e-05, 9.99941230e-01, 1.26756095e-05,
        4.63613277e-15, 8.53995243e-06, 2.90682664e-07, 6.83314904e-15,
        7.34585939e-08, 6.05854397e-16],
       [8.66851266e-08, 9.98676240e-01, 9.64881838e-05, 3.38244581e-06,
        1.02572631e-04, 5.55204542e-06, 6.75403953e-06, 7.73184816e-04,
        3.35330347e-04, 3.37306375e-07],
       [9.99951124e-01, 2.69727174e-09, 3.06216316e-05, 1.55055943e-07,
        8.10769318e-09, 3.55405336e-06, 6.91632886e-06, 9.15805956e-08,
        5.05572562e-09, 7.55222618e-06],
       [2.26475368e-06, 2.59165883e-10, 5.78497156e-06, 4.47667468e-08,
        9.97632384e-01, 4.71307580e-08, 4.98260051e-05, 6.82452228e-05,
        4.98468637e-07, 2.24086642e-03]], dtype=float32)>